### ISSUE TITLE
There are lots of nan in disparity files.

### ISSUE THREAD

**Issue by Qjizhi** [nju-ee/MODE-2022#3]
for example, `ep2_500drames/training/disp/011657_23_disp.npz`, there are lots of nan files, could you please fix it.

**Comment by AndyLiming** [comment]
The dataset captures a depth map at the position of camera 1 and transforms it into a disparity maps of different views.  There are occlusion points in other viewpoints(2,3,4). Thus, those disparity maps based on view 1 are dense(each pixel has a valid value). While for other views(cam pair 23,24,34), thedisparity maps are sparse. NaN value is filled into the occluded area to mark the invalid points. You can use numpy.isnan([array]) or torch.isnan([Tensor]) to filter this points and exclude these points from training and testing.
